version: '3.1'

services:

  app:
    container_name: tmi_web_cms
    image: drupal:8
    ports:
      - 11000:80
    volumes:
      - ./local/config:/var/www/config
      - ./local/modules:/var/www/html/modules
      - ./local/themes:/var/www/html/themes
      - ./local/site:/var/www/html/sites/default
      - ./local/core:/var/www/html/core
      - ./local/vendor:/var/www/html/vendor
      - ./local/libraries:/var/www/html/libraries
      - ./local/logs:/var/log
    restart: always

  db:
    container_name: tmi_web_db
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tmi_web
      - MYSQL_PASSWORD=tmi_web
      - MYSQL_DATABASE=tmi_web
    ports:
      - 11010:3306
    volumes:
      - ./local/data:/var/lib/mysql
    restart: always

  admin:
    container_name: tmi_web_admin
    image: adminer
    ports:
      - 11020:8080
    restart: always

# TODO: setup private network with nginx exposing only needed ports.

