<?php


function quicket_menu() {
  $items = array();
  
  $items['quicket/update_user'] = array(
    'title' => t('quicket update user'),
    'description' => t('quicket update user'),
    'page callback' => 'quicket_update_user',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'quicket_update_user.inc',
  );
  
  $items['quicket/loop'] = array(
    'title' => t('quicket loop to check user has a ticket code'),
    'description' => t('quicket update user'),
    'page callback' => 'quicket_loop',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'quicket_update_user.inc',
  );
  
  $items['quicket/quicket_qc_agree'] = array(
    'title' => t('quicket loop to check user has a ticket code'),
    'description' => t('quicket update user'),
    'page callback' => 'quicket_qc_agree',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'quicket_update_user.inc',
  );
  
  return $items;
}

