<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
<head>
<title>sandbox-ssekono-2028575 - For more information about this repository, visit the project page at http://drupal.org/sandbox/ssekono/2028575</title>
<meta name='generator' content='cgit v0.12'/>
<meta name='robots' content='index, nofollow'/>
<link rel='stylesheet' type='text/css' href='/cgit-data/cgit.css'/>
<link rel='shortcut icon' href='/favicon.ico'/>
<link rel='alternate' title='Atom feed' href='http://cgit.drupalcode.org/sandbox-ssekono-2028575/atom/charts_graphs_d3.module?h=7.x-1.x' type='application/atom+xml'/>
<link rel='vcs-git' href='git://git.drupal.org/sandbox/ssekono/2028575.git' title='sandbox-ssekono-2028575 Git repository'/>
</head>
<body>
<div id='cgit'><table id='header'>
<tr>
<td class='logo' rowspan='2'><a href='/'><img src='/cgit-data/logo.png' alt='cgit logo'/></a></td>
<td class='main'><a href='/'>index</a> : <a title='sandbox-ssekono-2028575' href='/sandbox-ssekono-2028575/'>sandbox-ssekono-2028575</a></td><td class='form'><form method='get' action=''>
<select name='h' onchange='this.form.submit();'>
<option value='7.x-1.x' selected='selected'>7.x-1.x</option>
</select> <input type='submit' name='' value='switch'/></form></td></tr>
<tr><td class='sub'>For more information about this repository, visit the project page at http://drupal.org/sandbox/ssekono/2028575</td><td class='sub right'>Drupal Git User (LDAP)</td></tr></table>
<table class='tabs'><tr><td>
<a href='/sandbox-ssekono-2028575/'>summary</a><a href='/sandbox-ssekono-2028575/refs/'>refs</a><a href='/sandbox-ssekono-2028575/log/charts_graphs_d3.module'>log</a><a class='active' href='/sandbox-ssekono-2028575/tree/charts_graphs_d3.module'>tree</a><a href='/sandbox-ssekono-2028575/commit/charts_graphs_d3.module'>commit</a><a href='/sandbox-ssekono-2028575/diff/charts_graphs_d3.module'>diff</a><a href='/sandbox-ssekono-2028575/stats/charts_graphs_d3.module'>stats</a></td><td class='form'><form class='right' method='get' action='/sandbox-ssekono-2028575/log/charts_graphs_d3.module'>
<select name='qt'>
<option value='grep'>log msg</option>
<option value='author'>author</option>
<option value='committer'>committer</option>
<option value='range'>range</option>
</select>
<input class='txt' type='text' size='10' name='q' value=''/>
<input type='submit' value='search'/>
</form>
</td></tr></table>
<div class='path'>path: <a href='/sandbox-ssekono-2028575/tree/'>root</a>/<a href='/sandbox-ssekono-2028575/tree/charts_graphs_d3.module'>charts_graphs_d3.module</a></div><div class='content'>blob: e9ce0d5718397eb26ba54b18bbcb9cb17e5ceb8e (<a href='/sandbox-ssekono-2028575/plain/charts_graphs_d3.module'>plain</a>)
<table summary='blob content' class='blob'>
<tr><td class='linenumbers'><pre><a id='n1' href='#n1'>1</a>
<a id='n2' href='#n2'>2</a>
<a id='n3' href='#n3'>3</a>
<a id='n4' href='#n4'>4</a>
<a id='n5' href='#n5'>5</a>
<a id='n6' href='#n6'>6</a>
<a id='n7' href='#n7'>7</a>
<a id='n8' href='#n8'>8</a>
<a id='n9' href='#n9'>9</a>
<a id='n10' href='#n10'>10</a>
<a id='n11' href='#n11'>11</a>
<a id='n12' href='#n12'>12</a>
<a id='n13' href='#n13'>13</a>
<a id='n14' href='#n14'>14</a>
<a id='n15' href='#n15'>15</a>
<a id='n16' href='#n16'>16</a>
<a id='n17' href='#n17'>17</a>
<a id='n18' href='#n18'>18</a>
<a id='n19' href='#n19'>19</a>
<a id='n20' href='#n20'>20</a>
<a id='n21' href='#n21'>21</a>
<a id='n22' href='#n22'>22</a>
<a id='n23' href='#n23'>23</a>
<a id='n24' href='#n24'>24</a>
<a id='n25' href='#n25'>25</a>
<a id='n26' href='#n26'>26</a>
<a id='n27' href='#n27'>27</a>
<a id='n28' href='#n28'>28</a>
<a id='n29' href='#n29'>29</a>
</pre></td>
<td class='lines'><pre><code><style>.highlight .hll { background-color: #ffffcc }
.highlight  { background: #ffffff; }
.highlight .c { color: #888888 } /* Comment */
.highlight .err { color: #a61717; background-color: #e3d2d2 } /* Error */
.highlight .k { color: #008800; font-weight: bold } /* Keyword */
.highlight .cm { color: #888888 } /* Comment.Multiline */
.highlight .cp { color: #cc0000; font-weight: bold } /* Comment.Preproc */
.highlight .c1 { color: #888888 } /* Comment.Single */
.highlight .cs { color: #cc0000; font-weight: bold; background-color: #fff0f0 } /* Comment.Special */
.highlight .gd { color: #000000; background-color: #ffdddd } /* Generic.Deleted */
.highlight .ge { font-style: italic } /* Generic.Emph */
.highlight .gr { color: #aa0000 } /* Generic.Error */
.highlight .gh { color: #303030 } /* Generic.Heading */
.highlight .gi { color: #000000; background-color: #ddffdd } /* Generic.Inserted */
.highlight .go { color: #888888 } /* Generic.Output */
.highlight .gp { color: #555555 } /* Generic.Prompt */
.highlight .gs { font-weight: bold } /* Generic.Strong */
.highlight .gu { color: #606060 } /* Generic.Subheading */
.highlight .gt { color: #aa0000 } /* Generic.Traceback */
.highlight .kc { color: #008800; font-weight: bold } /* Keyword.Constant */
.highlight .kd { color: #008800; font-weight: bold } /* Keyword.Declaration */
.highlight .kn { color: #008800; font-weight: bold } /* Keyword.Namespace */
.highlight .kp { color: #008800 } /* Keyword.Pseudo */
.highlight .kr { color: #008800; font-weight: bold } /* Keyword.Reserved */
.highlight .kt { color: #888888; font-weight: bold } /* Keyword.Type */
.highlight .m { color: #0000DD; font-weight: bold } /* Literal.Number */
.highlight .s { color: #dd2200; background-color: #fff0f0 } /* Literal.String */
.highlight .na { color: #336699 } /* Name.Attribute */
.highlight .nb { color: #003388 } /* Name.Builtin */
.highlight .nc { color: #bb0066; font-weight: bold } /* Name.Class */
.highlight .no { color: #003366; font-weight: bold } /* Name.Constant */
.highlight .nd { color: #555555 } /* Name.Decorator */
.highlight .ne { color: #bb0066; font-weight: bold } /* Name.Exception */
.highlight .nf { color: #0066bb; font-weight: bold } /* Name.Function */
.highlight .nl { color: #336699; font-style: italic } /* Name.Label */
.highlight .nn { color: #bb0066; font-weight: bold } /* Name.Namespace */
.highlight .py { color: #336699; font-weight: bold } /* Name.Property */
.highlight .nt { color: #bb0066; font-weight: bold } /* Name.Tag */
.highlight .nv { color: #336699 } /* Name.Variable */
.highlight .ow { color: #008800 } /* Operator.Word */
.highlight .w { color: #bbbbbb } /* Text.Whitespace */
.highlight .mf { color: #0000DD; font-weight: bold } /* Literal.Number.Float */
.highlight .mh { color: #0000DD; font-weight: bold } /* Literal.Number.Hex */
.highlight .mi { color: #0000DD; font-weight: bold } /* Literal.Number.Integer */
.highlight .mo { color: #0000DD; font-weight: bold } /* Literal.Number.Oct */
.highlight .sb { color: #dd2200; background-color: #fff0f0 } /* Literal.String.Backtick */
.highlight .sc { color: #dd2200; background-color: #fff0f0 } /* Literal.String.Char */
.highlight .sd { color: #dd2200; background-color: #fff0f0 } /* Literal.String.Doc */
.highlight .s2 { color: #dd2200; background-color: #fff0f0 } /* Literal.String.Double */
.highlight .se { color: #0044dd; background-color: #fff0f0 } /* Literal.String.Escape */
.highlight .sh { color: #dd2200; background-color: #fff0f0 } /* Literal.String.Heredoc */
.highlight .si { color: #3333bb; background-color: #fff0f0 } /* Literal.String.Interpol */
.highlight .sx { color: #22bb22; background-color: #f0fff0 } /* Literal.String.Other */
.highlight .sr { color: #008800; background-color: #fff0ff } /* Literal.String.Regex */
.highlight .s1 { color: #dd2200; background-color: #fff0f0 } /* Literal.String.Single */
.highlight .ss { color: #aa6600; background-color: #fff0f0 } /* Literal.String.Symbol */
.highlight .bp { color: #003388 } /* Name.Builtin.Pseudo */
.highlight .vc { color: #336699 } /* Name.Variable.Class */
.highlight .vg { color: #dd7700 } /* Name.Variable.Global */
.highlight .vi { color: #3333bb } /* Name.Variable.Instance */
.highlight .il { color: #0000DD; font-weight: bold } /* Literal.Number.Integer.Long */</style><div class="highlight"><pre><span class="cp">&lt;?php</span>
<span class="sd">/**</span>
<span class="sd"> * @file</span>
<span class="sd"> * drupal module file implementing d3 charting.</span>
<span class="sd"> */</span>

<span class="sd">/**</span>
<span class="sd"> * Implements hook_chartgraph_provider().</span>
<span class="sd"> */</span>
<span class="k">function</span> <span class="nf">charts_graphs_d3_chartgraph_provider</span><span class="p">()</span> <span class="p">{</span>
  <span class="nv">$provider</span> <span class="o">=</span> <span class="k">array</span><span class="p">(</span>
    <span class="c1">// Must befull path.</span>
    <span class="s1">&#39;path&#39;</span> <span class="o">=&gt;</span> <span class="nx">drupal_get_path</span><span class="p">(</span><span class="s1">&#39;module&#39;</span><span class="p">,</span> <span class="s1">&#39;charts_graphs_d3&#39;</span><span class="p">)</span> <span class="o">.</span> <span class="s1">&#39;/charts_graphs_d3.class.inc&#39;</span><span class="p">,</span>
    <span class="c1">// Implementation class&#39; name.</span>
    <span class="s1">&#39;clazz&#39;</span> <span class="o">=&gt;</span> <span class="s1">&#39;ChartsGraphsD3&#39;</span><span class="p">,</span>
    <span class="c1">// Name used when invoking through a factory method.</span>
    <span class="s1">&#39;name&#39;</span> <span class="o">=&gt;</span> <span class="s1">&#39;d3&#39;</span><span class="p">,</span>
    <span class="s1">&#39;nice_name&#39;</span> <span class="o">=&gt;</span> <span class="s1">&#39;D3&#39;</span><span class="p">,</span>
    <span class="s1">&#39;chart_types&#39;</span> <span class="o">=&gt;</span> <span class="k">array</span><span class="p">(</span>
      <span class="s1">&#39;LineGraph&#39;</span> <span class="o">=&gt;</span> <span class="nx">t</span><span class="p">(</span><span class="s1">&#39;Line Graph&#39;</span><span class="p">),</span>
      <span class="s1">&#39;ColumnChart&#39;</span> <span class="o">=&gt;</span> <span class="nx">t</span><span class="p">(</span><span class="s1">&#39;Column Chart&#39;</span><span class="p">),</span>
      <span class="s1">&#39;BarChart&#39;</span> <span class="o">=&gt;</span> <span class="nx">t</span><span class="p">(</span><span class="s1">&#39;Bar Chart&#39;</span><span class="p">),</span>
      <span class="s1">&#39;PieChart&#39;</span> <span class="o">=&gt;</span> <span class="nx">t</span><span class="p">(</span><span class="s1">&#39;Pie Chart&#39;</span><span class="p">),</span>
      <span class="s1">&#39;DonutChart&#39;</span> <span class="o">=&gt;</span> <span class="nx">t</span><span class="p">(</span><span class="s1">&#39;Donut Chart&#39;</span><span class="p">),</span>
    <span class="p">),</span>
  <span class="p">);</span>

  <span class="k">return</span> <span class="p">(</span><span class="nx">object</span><span class="p">)</span> <span class="nv">$provider</span><span class="p">;</span>
<span class="p">}</span>
</pre></div>
</code></pre></td></tr></table>
</div> <!-- class=content -->
<div class='footer'>generated by <a href='http://git.zx2c4.com/cgit/about/'>cgit v0.12</a> at 2017-02-12 13:11:48 (GMT)</div>
</div> <!-- id=cgit -->
</body>
</html>
